### ISSUE TITLE
tf核心库的ff指的是哪个库呢？

### ISSUE THREAD

**Issue by little7Li** [ilredirana/estimator_models#1]
estimator_inception_v3.py 
line 241 的注释            
不想使用slim的这个方法，考虑修改为tf核心库的ff
请教您一下，这里提到的ff是什么呢？

**Comment by ilredirana** [comment]
抱歉呀，我想了好久也没想起来。。。因为后期我用了改用了eager execution模式，用的是
`with tfe.restore_variables_on_create(tf.train.latest_checkpoint(restore_path)):`
上下文管理器来恢复保存的参数。
仔细想了想，是不是想打“方法”然后直接打成了“ff”呀。。。😭😭😭

**Comment by little7Li** [comment]
哈哈，感谢！看来我也该改用eager了。另外想问您一下，HND手写字母数据集哪里可以找到呢？

**Comment by ilredirana** [comment]
不客气，在这下的 http://www.ee.surrey.ac.uk/CVSSP/demos/chars74k/#download

**Comment by little7Li** [comment]
谢谢！你的代码真的对我帮助很大！

**Comment by little7Li** [comment]
我查了一下，可能是这个
tf.contrib.framework.get_variables_to_restore

**Comment by ilredirana** [comment]
> 我查了一下，可能是这个
> tf.contrib.framework.get_variables_to_restore

应该是后出的，和slim库里的差不多。
